theme: minima

twitter_username: dhunten
github_username:  dhunten
dribbble_username: dhunten
instagram_username: urmim
linkedin_username: dhunten

google_analytics: UA-29682729-1

url: dhunten.com
author: derek
tagline: Beep boop ha, ha.
